  scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets:
        - host.docker.internal:9090

  - job_name: mq
    metrics_path: "/metrics"    
    static_configs:
      - targets:
        - host.docker.internal:15692
    basic_auth:
      username: "broker"
      password: "CHANGEME"

  - job_name: json_exporter
    static_configs:
      - targets:
        - host.docker.internal:7979 

  ## gather the metrics from third party json sources, via the json exporter
  - job_name: json
    scrape_interval: 0s20ms
    metrics_path: /probe
    params:
      module: [default]
    static_configs:
      - targets:
        - http://host.docker.internal:8080/data.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
      ## Location of the json exporter's real <hostname>:<port>
        replacement: host.docker.internal:7979  